### ISSUE TITLE
It doesn't work with Redmine 4.0.x

### ISSUE THREAD

**Issue by linkcn** [arkhitech/redmine_update_reminder#15]
When I run "RAILS_ENV=production rake redmine_update_reminder:send_issue_reminders" I got below error messages, could someone help on this?

** Invoke redmine_update_reminder:send_issue_reminders (first_time)
** Invoke environment (first_time)
** Execute environment
Rails Error: Unable to access log file. Please ensure that /srv/redmine-4.0/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /srv/redmine-4.0/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /srv/redmine-4.0/config/routes.rb:364)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /srv/redmine-4.0/config/routes.rb:364)
** Execute redmine_update_reminder:send_issue_reminders
rake aborted!
NameError: undefined local variable or method `cc_email_address' for #<RemindingMailer:0x000055c73769f718>
Did you mean?  cc_email_addresses
               cc_email_addresses
/srv/redmine-4.0/plugins/redmine_update_reminder/app/models/reminding_mailer.rb:38:in `cc_email_addresses'
/srv/redmine-4.0/plugins/redmine_update_reminder/app/models/reminding_mailer.rb:47:in `reminder_issue_email'
/usr/share/gems/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:194:in `process_action'
/usr/share/gems/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/share/gems/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/share/gems/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/rescuable.rb:25:in `block in process'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/rescuable.rb:24:in `process'
/usr/share/gems/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:607:in `block in process'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/base.rb:606:in `process'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:122:in `tap'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
/usr/share/gems/gems/actionmailer-5.2.4.2/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/srv/redmine-4.0/plugins/redmine_update_reminder/lib/tasks/reminder.rake:131:in `block (2 levels) in send_issue_tracker_reminders'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
/srv/redmine-4.0/plugins/redmine_update_reminder/lib/tasks/reminder.rake:130:in `block in send_issue_tracker_reminders'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/usr/share/gems/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/srv/redmine-4.0/plugins/redmine_update_reminder/lib/tasks/reminder.rake:121:in `send_issue_tracker_reminders'
/srv/redmine-4.0/plugins/redmine_update_reminder/lib/tasks/reminder.rake:161:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:226:in `mon_synchronize'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/share/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine_update_reminder:send_issue_reminders

**Comment by linkcn** [comment]
fixed with commit 993951d40cb6e31fb56b3f65511ae7a07fa29844
